### ISSUE TITLE
File Upload fails due to added Content-Type header

### ISSUE THREAD

**Issue by Dogfalo** [ava/use-http#213]
**Describe the bug**
File Upload fails due to `Content-Type` header being automatically added when multipart/form-data is expected

Fix: Remove the default content-type for POST and PUT that is added here https://github.com/alex-cory/use-http/blob/master/src/doFetchArgs.ts#L60

see here for more information: https://github.com/github/fetch/issues/505#issuecomment-293064470

**Comment by alex-cory** [comment]
will take a look.

**Comment by alex-cory** [comment]
As a workaround in the meantime, you can remove that header like
```js
const { ... } = useFetch(opts => {
  delete opts['Content-Type']
  return opts
})
```

**Comment by alex-cory** [comment]
I'm trying to decide what is more useful to more use cases. Adding the `Content-Type: application/json` header or not. I see [axios](https://github.com/axios/axios/blob/6642ca9aa1efae47b1a9d3ce3adc98416318661c/lib/defaults.js#L7) has `'Content-Type': 'application/x-www-form-urlencoded'` as the default.

I'm down to remove this, just want to make sure it's the best decision.

**Comment by alex-cory** [comment]
This should now work as of `v0.4.4`. If the issue persists, let me know and I'll reopen the issue.

**Comment by sbichenko** [comment]
This doesn't seem to work, at least in React Native. It seems that the [isObject](https://github.com/ava/use-http/blob/master/src/utils.ts#L75) test evaluates to true when passed `FormData`. This is because React Native relies on an [implementation of `FormData`](https://github.com/facebook/react-native/blob/master/Libraries/Network/FormData.js) that doesn't have `toStringTag` set (just like [this one](https://github.com/form-data/form-data/issues/396)). As a result, the [`isBodyObject` check](https://github.com/ava/use-http/blob/master/src/doFetchArgs.ts#L40) in doFetchArgs evaluates to true, and FormData is stringified, and then incorrect Content-Type is added.

**Comment by alex-cory** [comment]
Are you able to work around this for now? I can fix this unless you want to submit a PR.

**Comment by sbichenko** [comment]
I don't think I can work around this. The workaround from your reply at the top doesn't work for me (haven't figured out why yet).

I have a branch ready with a simple fix that I've tested manually, but
1. When trying to push to the repo I get "fatal: Could not read from remote repository." -- do I need some additional permissions or is this something on my side?
2. I did not add a test for this case because I'm not sure how to go about adding a React Native test to the test suite.

**Comment by alex-cory** [comment]
You need to
1. fork the repo
2. clone your fork
3. make your changes
4. push your changes (to your fork)
5. make a pull request (where you can compare my master branch to your forked repo:branch)

**Comment by sbichenko** [comment]
Thanks, that's great! I think it would be worth adding the instructions to the contributor guidelines. Here's the PR: https://github.com/ava/use-http/pull/249

**Comment by alex-cory** [comment]
@sbichenko added a [contributions.md](https://github.com/ava/use-http/blob/master/.github/contributing.md)
